#!/bin/bash
# vim:set ft=sh:

export TERM='xterm-256color'

[[ -f ~/.aliases_linux ]] && . ~/.aliases_linux

export VCPROMPT_FORMAT="%b%u%m"

export XDG_RUNTIME_DIR="/run/user/$UID"
export DBUS_SESSION_BUS_ADDRESS="unix:path=${XDG_RUNTIME_DIR}/bus"
export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"
