#!/bin/sh

DISTRACTION_MAC_APPS=('Twitter.app' 'Flowdock.app')
DISTRACTION_LINUX_APPS=( )

function concentrate_apps() {
    # Move all distracting apps to a hidden dotfile prefix
    if [[ $(uname) = 'Darwin' ]]; then
        for app in ${DISTRACTION_MAC_APPS[@]}; do
            if [[ -e "/Applications/$app" ]]; then
                sudo mv "/Applications/$app" "/Applications/.distract.$app"
            fi
        done
    fi
}

function distract_apps() {
    # Move all hidden distracted apps back to their original location
    if [[ $(uname) = 'Darwin' ]]; then
        for app in ${DISTRACTION_MAC_APPS[@]}; do
            if [[ -e "/Applications/.distract.$app" ]]; then
                sudo mv "/Applications/.distract.$app" "/Applications/$app"
            fi
        done
    fi
}

function distract_hosts() {
    # Comment out all lines in /etc/hosts ending in #distraction
    sudo sed -i '' -e 's/\(^[^#].*\)#distraction$/#\1#distraction/' /etc/hosts
}

function concentrate_hosts() {
    # Uncomment all lines in /etc/hosts ending in #distraction
    sudo sed -i '' -e 's/^#\(.*\)#distraction$/\1#distraction/' /etc/hosts
}

function concentrate() {
    concentrate_hosts
    concentrate_apps
    sudo dscacheutil -flushcache
}

function distract() {
    distract_hosts
    distract_apps
    sudo dscacheutil -flushcache
}
